var searchData=
[
  ['range_11942',['Range',['../classcv_1_1_range.html',1,'cv']]],
  ['rebind_11943',['rebind',['../classcv_1_1_allocator_1_1rebind.html',1,'cv::Allocator']]],
  ['recipeauditor_11944',['RecipeAuditor',['../classcom_1_1example_1_1recipeengine_1_1recipe_1_1auditor_1_1_recipe_auditor.html',1,'com::example::recipeengine::recipe::auditor']]],
  ['recipecontext_11945',['RecipeContext',['../classcom_1_1example_1_1recipeengine_1_1instruction_1_1handler_1_1cook_1_1status_1_1_recipe_context.html',1,'com::example::recipeengine::instruction::handler::cook::status']]],
  ['recipecontexttest_11946',['RecipeContextTest',['../classcom_1_1example_1_1recipeengine_1_1instruction_1_1handler_1_1cook_1_1status_1_1_recipe_context_test.html',1,'com::example::recipeengine::instruction::handler::cook::status']]],
  ['recipereader_11947',['RecipeReader',['../classcom_1_1example_1_1recipeengine_1_1recipe_1_1reader_1_1_recipe_reader.html',1,'com::example::recipeengine::recipe::reader']]],
  ['recipereadercomponent_11948',['RecipeReaderComponent',['../interfacecom_1_1example_1_1recipeengine_1_1recipe_1_1reader_1_1_recipe_reader_component.html',1,'com::example::recipeengine::recipe::reader']]],
  ['recipereadermodule_11949',['RecipeReaderModule',['../classcom_1_1example_1_1recipeengine_1_1recipe_1_1reader_1_1_recipe_reader_module.html',1,'com::example::recipeengine::recipe::reader']]],
  ['recipereadertest_11950',['RecipeReaderTest',['../classcom_1_1example_1_1recipeengine_1_1recipe_1_1reader_1_1_recipe_reader_test.html',1,'com::example::recipeengine::recipe::reader']]],
  ['rect_5f_11951',['Rect_',['../classcv_1_1_rect__.html',1,'cv']]],
  ['rectifierfactory_11952',['RectifierFactory',['../classcom_1_1example_1_1recipeengine_1_1instruction_1_1rectifier_1_1_rectifier_factory.html',1,'com::example::recipeengine::instruction::rectifier']]],
  ['regionlayer_11953',['RegionLayer',['../classcv_1_1dnn_1_1_region_layer.html',1,'cv::dnn']]],
  ['relu6layer_11954',['ReLU6Layer',['../classcv_1_1dnn_1_1_re_l_u6_layer.html',1,'cv::dnn']]],
  ['relulayer_11955',['ReLULayer',['../classcv_1_1dnn_1_1_re_l_u_layer.html',1,'cv::dnn']]],
  ['reorglayer_11956',['ReorgLayer',['../classcv_1_1dnn_1_1_reorg_layer.html',1,'cv::dnn']]],
  ['request_11957',['Request',['../classsom_1_1instruction_1_1request_1_1_request.html',1,'som::instruction::request']]],
  ['requestbuilder_11958',['RequestBuilder',['../interfacesom_1_1hardware_1_1request_1_1builder_1_1_request_builder.html',1,'som::hardware::request::builder']]],
  ['requestexecutor_11959',['RequestExecutor',['../class_request_executor.html',1,'']]],
  ['requesthandler_11960',['RequestHandler',['../classsom_1_1hardware_1_1request_1_1handler_1_1_request_handler.html',1,'som::hardware::request::handler']]],
  ['requesthandlertest_11961',['RequestHandlerTest',['../classsom_1_1hardware_1_1request_1_1handler_1_1_request_handler_test.html',1,'som::hardware::request::handler']]],
  ['requestparameters_11962',['RequestParameters',['../enumsom_1_1instruction_1_1request_1_1_request_parameters.html',1,'som::instruction::request']]],
  ['requesttest_11963',['RequestTest',['../classsom_1_1instruction_1_1request_1_1_request_test.html',1,'som::instruction::request']]],
  ['requesttype_11964',['RequestType',['../enumsom_1_1instruction_1_1request_1_1_request_type.html',1,'som.instruction.request.RequestType'],['../enumsom_1_1hardware_1_1message_1_1_request_type.html',1,'som.hardware.message.RequestType']]],
  ['resetcbcomponent_11965',['ResetCbComponent',['../classcom_1_1example_1_1recipeengine_1_1util_1_1debug_1_1components_1_1cb_1_1_reset_cb_component.html',1,'com::example::recipeengine::util::debug::components::cb']]],
  ['reshapelayer_11966',['ReshapeLayer',['../classcv_1_1dnn_1_1_reshape_layer.html',1,'cv::dnn']]],
  ['resizelayer_11967',['ResizeLayer',['../classcv_1_1dnn_1_1_resize_layer.html',1,'cv::dnn']]],
  ['response_11968',['Response',['../classsom_1_1hardware_1_1response_1_1_response.html',1,'som::hardware::response']]],
  ['retry_11969',['Retry',['../classcom_1_1example_1_1recipeengine_1_1util_1_1_retry.html',1,'com::example::recipeengine::util']]],
  ['retrytest_11970',['RetryTest',['../classcom_1_1example_1_1recipeengine_1_1util_1_1_retry_test.html',1,'com::example::recipeengine::util']]],
  ['rng_11971',['RNG',['../classcv_1_1_r_n_g.html',1,'cv']]],
  ['rng_5fmt19937_11972',['RNG_MT19937',['../classcv_1_1_r_n_g___m_t19937.html',1,'cv']]],
  ['rnnlayer_11973',['RNNLayer',['../classcv_1_1dnn_1_1_r_n_n_layer.html',1,'cv::dnn']]],
  ['rotatedrect_11974',['RotatedRect',['../classcv_1_1_rotated_rect.html',1,'cv']]],
  ['rotationwarper_11975',['RotationWarper',['../classcv_1_1detail_1_1_rotation_warper.html',1,'cv::detail']]],
  ['rotationwarperbase_11976',['RotationWarperBase',['../classcv_1_1detail_1_1_rotation_warper_base.html',1,'cv::detail']]],
  ['rotationwarperbase_3c_20compressedrectilinearportraitprojector_20_3e_11977',['RotationWarperBase&lt; CompressedRectilinearPortraitProjector &gt;',['../classcv_1_1detail_1_1_rotation_warper_base.html',1,'cv::detail']]],
  ['rotationwarperbase_3c_20compressedrectilinearprojector_20_3e_11978',['RotationWarperBase&lt; CompressedRectilinearProjector &gt;',['../classcv_1_1detail_1_1_rotation_warper_base.html',1,'cv::detail']]],
  ['rotationwarperbase_3c_20cylindricalportraitprojector_20_3e_11979',['RotationWarperBase&lt; CylindricalPortraitProjector &gt;',['../classcv_1_1detail_1_1_rotation_warper_base.html',1,'cv::detail']]],
  ['rotationwarperbase_3c_20cylindricalprojector_20_3e_11980',['RotationWarperBase&lt; CylindricalProjector &gt;',['../classcv_1_1detail_1_1_rotation_warper_base.html',1,'cv::detail']]],
  ['rotationwarperbase_3c_20fisheyeprojector_20_3e_11981',['RotationWarperBase&lt; FisheyeProjector &gt;',['../classcv_1_1detail_1_1_rotation_warper_base.html',1,'cv::detail']]],
  ['rotationwarperbase_3c_20mercatorprojector_20_3e_11982',['RotationWarperBase&lt; MercatorProjector &gt;',['../classcv_1_1detail_1_1_rotation_warper_base.html',1,'cv::detail']]],
  ['rotationwarperbase_3c_20paniniportraitprojector_20_3e_11983',['RotationWarperBase&lt; PaniniPortraitProjector &gt;',['../classcv_1_1detail_1_1_rotation_warper_base.html',1,'cv::detail']]],
  ['rotationwarperbase_3c_20paniniprojector_20_3e_11984',['RotationWarperBase&lt; PaniniProjector &gt;',['../classcv_1_1detail_1_1_rotation_warper_base.html',1,'cv::detail']]],
  ['rotationwarperbase_3c_20planeportraitprojector_20_3e_11985',['RotationWarperBase&lt; PlanePortraitProjector &gt;',['../classcv_1_1detail_1_1_rotation_warper_base.html',1,'cv::detail']]],
  ['rotationwarperbase_3c_20planeprojector_20_3e_11986',['RotationWarperBase&lt; PlaneProjector &gt;',['../classcv_1_1detail_1_1_rotation_warper_base.html',1,'cv::detail']]],
  ['rotationwarperbase_3c_20sphericalportraitprojector_20_3e_11987',['RotationWarperBase&lt; SphericalPortraitProjector &gt;',['../classcv_1_1detail_1_1_rotation_warper_base.html',1,'cv::detail']]],
  ['rotationwarperbase_3c_20sphericalprojector_20_3e_11988',['RotationWarperBase&lt; SphericalProjector &gt;',['../classcv_1_1detail_1_1_rotation_warper_base.html',1,'cv::detail']]],
  ['rotationwarperbase_3c_20stereographicprojector_20_3e_11989',['RotationWarperBase&lt; StereographicProjector &gt;',['../classcv_1_1detail_1_1_rotation_warper_base.html',1,'cv::detail']]],
  ['rotationwarperbase_3c_20transversemercatorprojector_20_3e_11990',['RotationWarperBase&lt; TransverseMercatorProjector &gt;',['../classcv_1_1detail_1_1_rotation_warper_base.html',1,'cv::detail']]]
];
