var dir_4da9ae17cd6fd324a5da793b14b94e0f =
[
    [ "opencl_clamdblas.hpp", "autogenerated_2opencl__clamdblas_8hpp.html", "autogenerated_2opencl__clamdblas_8hpp" ],
    [ "opencl_clamdfft.hpp", "autogenerated_2opencl__clamdfft_8hpp.html", "autogenerated_2opencl__clamdfft_8hpp" ],
    [ "opencl_core.hpp", "autogenerated_2opencl__core_8hpp.html", "autogenerated_2opencl__core_8hpp" ],
    [ "opencl_core_wrappers.hpp", "autogenerated_2opencl__core__wrappers_8hpp.html", "autogenerated_2opencl__core__wrappers_8hpp" ],
    [ "opencl_gl.hpp", "autogenerated_2opencl__gl_8hpp.html", "autogenerated_2opencl__gl_8hpp" ],
    [ "opencl_gl_wrappers.hpp", "autogenerated_2opencl__gl__wrappers_8hpp.html", null ]
];