var namespacecv =
[
    [ "cuda", "namespacecv_1_1cuda.html", "namespacecv_1_1cuda" ],
    [ "detail", "namespacecv_1_1detail.html", "namespacecv_1_1detail" ],
    [ "directx", "namespacecv_1_1directx.html", null ],
    [ "dnn", "namespacecv_1_1dnn.html", "namespacecv_1_1dnn" ],
    [ "flann", "namespacecv_1_1flann.html", "namespacecv_1_1flann" ],
    [ "hal", "namespacecv_1_1hal.html", "namespacecv_1_1hal" ],
    [ "instr", "namespacecv_1_1instr.html", "namespacecv_1_1instr" ],
    [ "ocl", "namespacecv_1_1ocl.html", "namespacecv_1_1ocl" ],
    [ "ogl", "namespacecv_1_1ogl.html", "namespacecv_1_1ogl" ],
    [ "sfinae", "namespacecv_1_1sfinae.html", "namespacecv_1_1sfinae" ],
    [ "traits", "namespacecv_1_1traits.html", "namespacecv_1_1traits" ],
    [ "utils", "namespacecv_1_1utils.html", "namespacecv_1_1utils" ],
    [ "va_intel", "namespacecv_1_1va__intel.html", null ],
    [ "_InputArray", "classcv_1_1___input_array.html", "classcv_1_1___input_array" ],
    [ "_InputOutputArray", "classcv_1_1___input_output_array.html", "classcv_1_1___input_output_array" ],
    [ "_OutputArray", "classcv_1_1___output_array.html", "classcv_1_1___output_array" ],
    [ "Accumulator", "structcv_1_1_accumulator.html", "structcv_1_1_accumulator" ],
    [ "Accumulator< char >", "structcv_1_1_accumulator_3_01char_01_4.html", "structcv_1_1_accumulator_3_01char_01_4" ],
    [ "Accumulator< short >", "structcv_1_1_accumulator_3_01short_01_4.html", "structcv_1_1_accumulator_3_01short_01_4" ],
    [ "Accumulator< unsigned char >", "structcv_1_1_accumulator_3_01unsigned_01char_01_4.html", "structcv_1_1_accumulator_3_01unsigned_01char_01_4" ],
    [ "Accumulator< unsigned short >", "structcv_1_1_accumulator_3_01unsigned_01short_01_4.html", "structcv_1_1_accumulator_3_01unsigned_01short_01_4" ],
    [ "AffineWarper", "classcv_1_1_affine_warper.html", "classcv_1_1_affine_warper" ],
    [ "AgastFeatureDetector", "classcv_1_1_agast_feature_detector.html", "classcv_1_1_agast_feature_detector" ],
    [ "AKAZE", "classcv_1_1_a_k_a_z_e.html", "classcv_1_1_a_k_a_z_e" ],
    [ "Algorithm", "classcv_1_1_algorithm.html", "classcv_1_1_algorithm" ],
    [ "AlignExposures", "classcv_1_1_align_exposures.html", "classcv_1_1_align_exposures" ],
    [ "AlignMTB", "classcv_1_1_align_m_t_b.html", "classcv_1_1_align_m_t_b" ],
    [ "Allocator", "classcv_1_1_allocator.html", "classcv_1_1_allocator" ],
    [ "AsyncArray", "classcv_1_1_async_array.html", "classcv_1_1_async_array" ],
    [ "AsyncPromise", "classcv_1_1_async_promise.html", "classcv_1_1_async_promise" ],
    [ "AutoBuffer", "classcv_1_1_auto_buffer.html", "classcv_1_1_auto_buffer" ],
    [ "BackgroundSubtractor", "classcv_1_1_background_subtractor.html", "classcv_1_1_background_subtractor" ],
    [ "BackgroundSubtractorKNN", "classcv_1_1_background_subtractor_k_n_n.html", "classcv_1_1_background_subtractor_k_n_n" ],
    [ "BackgroundSubtractorMOG2", "classcv_1_1_background_subtractor_m_o_g2.html", "classcv_1_1_background_subtractor_m_o_g2" ],
    [ "BaseCascadeClassifier", "classcv_1_1_base_cascade_classifier.html", "classcv_1_1_base_cascade_classifier" ],
    [ "BFMatcher", "classcv_1_1_b_f_matcher.html", "classcv_1_1_b_f_matcher" ],
    [ "BOWImgDescriptorExtractor", "classcv_1_1_b_o_w_img_descriptor_extractor.html", "classcv_1_1_b_o_w_img_descriptor_extractor" ],
    [ "BOWKMeansTrainer", "classcv_1_1_b_o_w_k_means_trainer.html", "classcv_1_1_b_o_w_k_means_trainer" ],
    [ "BOWTrainer", "classcv_1_1_b_o_w_trainer.html", "classcv_1_1_b_o_w_trainer" ],
    [ "BRISK", "classcv_1_1_b_r_i_s_k.html", "classcv_1_1_b_r_i_s_k" ],
    [ "BufferPoolController", "classcv_1_1_buffer_pool_controller.html", "classcv_1_1_buffer_pool_controller" ],
    [ "CalibrateCRF", "classcv_1_1_calibrate_c_r_f.html", "classcv_1_1_calibrate_c_r_f" ],
    [ "CalibrateDebevec", "classcv_1_1_calibrate_debevec.html", "classcv_1_1_calibrate_debevec" ],
    [ "CalibrateRobertson", "classcv_1_1_calibrate_robertson.html", "classcv_1_1_calibrate_robertson" ],
    [ "CascadeClassifier", "classcv_1_1_cascade_classifier.html", "classcv_1_1_cascade_classifier" ],
    [ "CirclesGridFinderParameters", "structcv_1_1_circles_grid_finder_parameters.html", "structcv_1_1_circles_grid_finder_parameters" ],
    [ "CLAHE", "classcv_1_1_c_l_a_h_e.html", "classcv_1_1_c_l_a_h_e" ],
    [ "CommandLineParser", "classcv_1_1_command_line_parser.html", "classcv_1_1_command_line_parser" ],
    [ "Complex", "classcv_1_1_complex.html", "classcv_1_1_complex" ],
    [ "CompressedRectilinearPortraitWarper", "classcv_1_1_compressed_rectilinear_portrait_warper.html", "classcv_1_1_compressed_rectilinear_portrait_warper" ],
    [ "CompressedRectilinearWarper", "classcv_1_1_compressed_rectilinear_warper.html", "classcv_1_1_compressed_rectilinear_warper" ],
    [ "ConjGradSolver", "classcv_1_1_conj_grad_solver.html", null ],
    [ "CylindricalWarper", "classcv_1_1_cylindrical_warper.html", "classcv_1_1_cylindrical_warper" ],
    [ "DataDepth", "classcv_1_1_data_depth.html", "classcv_1_1_data_depth" ],
    [ "DataType", "classcv_1_1_data_type.html", null ],
    [ "DataType< bool >", "classcv_1_1_data_type_3_01bool_01_4.html", "classcv_1_1_data_type_3_01bool_01_4" ],
    [ "DataType< char >", "classcv_1_1_data_type_3_01char_01_4.html", "classcv_1_1_data_type_3_01char_01_4" ],
    [ "DataType< Complex< _Tp > >", "classcv_1_1_data_type_3_01_complex_3_01___tp_01_4_01_4.html", "classcv_1_1_data_type_3_01_complex_3_01___tp_01_4_01_4" ],
    [ "DataType< double >", "classcv_1_1_data_type_3_01double_01_4.html", "classcv_1_1_data_type_3_01double_01_4" ],
    [ "DataType< float >", "classcv_1_1_data_type_3_01float_01_4.html", "classcv_1_1_data_type_3_01float_01_4" ],
    [ "DataType< float16_t >", "classcv_1_1_data_type_3_01float16__t_01_4.html", "classcv_1_1_data_type_3_01float16__t_01_4" ],
    [ "DataType< int >", "classcv_1_1_data_type_3_01int_01_4.html", "classcv_1_1_data_type_3_01int_01_4" ],
    [ "DataType< Matx< _Tp, m, n > >", "classcv_1_1_data_type_3_01_matx_3_01___tp_00_01m_00_01n_01_4_01_4.html", "classcv_1_1_data_type_3_01_matx_3_01___tp_00_01m_00_01n_01_4_01_4" ],
    [ "DataType< Moments >", "classcv_1_1_data_type_3_01_moments_01_4.html", "classcv_1_1_data_type_3_01_moments_01_4" ],
    [ "DataType< Point3_< _Tp > >", "classcv_1_1_data_type_3_01_point3___3_01___tp_01_4_01_4.html", "classcv_1_1_data_type_3_01_point3___3_01___tp_01_4_01_4" ],
    [ "DataType< Point_< _Tp > >", "classcv_1_1_data_type_3_01_point___3_01___tp_01_4_01_4.html", "classcv_1_1_data_type_3_01_point___3_01___tp_01_4_01_4" ],
    [ "DataType< Range >", "classcv_1_1_data_type_3_01_range_01_4.html", "classcv_1_1_data_type_3_01_range_01_4" ],
    [ "DataType< Rect_< _Tp > >", "classcv_1_1_data_type_3_01_rect___3_01___tp_01_4_01_4.html", "classcv_1_1_data_type_3_01_rect___3_01___tp_01_4_01_4" ],
    [ "DataType< RotatedRect >", "classcv_1_1_data_type_3_01_rotated_rect_01_4.html", "classcv_1_1_data_type_3_01_rotated_rect_01_4" ],
    [ "DataType< Scalar_< _Tp > >", "classcv_1_1_data_type_3_01_scalar___3_01___tp_01_4_01_4.html", "classcv_1_1_data_type_3_01_scalar___3_01___tp_01_4_01_4" ],
    [ "DataType< schar >", "classcv_1_1_data_type_3_01schar_01_4.html", "classcv_1_1_data_type_3_01schar_01_4" ],
    [ "DataType< short >", "classcv_1_1_data_type_3_01short_01_4.html", "classcv_1_1_data_type_3_01short_01_4" ],
    [ "DataType< Size_< _Tp > >", "classcv_1_1_data_type_3_01_size___3_01___tp_01_4_01_4.html", "classcv_1_1_data_type_3_01_size___3_01___tp_01_4_01_4" ],
    [ "DataType< uchar >", "classcv_1_1_data_type_3_01uchar_01_4.html", "classcv_1_1_data_type_3_01uchar_01_4" ],
    [ "DataType< ushort >", "classcv_1_1_data_type_3_01ushort_01_4.html", "classcv_1_1_data_type_3_01ushort_01_4" ],
    [ "DataType< Vec< _Tp, cn > >", "classcv_1_1_data_type_3_01_vec_3_01___tp_00_01cn_01_4_01_4.html", "classcv_1_1_data_type_3_01_vec_3_01___tp_00_01cn_01_4_01_4" ],
    [ "DefaultDeleter", "structcv_1_1_default_deleter.html", null ],
    [ "DefaultDeleter< CvCapture >", "structcv_1_1_default_deleter_3_01_cv_capture_01_4.html", "structcv_1_1_default_deleter_3_01_cv_capture_01_4" ],
    [ "DefaultDeleter< CvHaarClassifierCascade >", "structcv_1_1_default_deleter_3_01_cv_haar_classifier_cascade_01_4.html", "structcv_1_1_default_deleter_3_01_cv_haar_classifier_cascade_01_4" ],
    [ "DefaultDeleter< CvVideoWriter >", "structcv_1_1_default_deleter_3_01_cv_video_writer_01_4.html", "structcv_1_1_default_deleter_3_01_cv_video_writer_01_4" ],
    [ "DenseOpticalFlow", "classcv_1_1_dense_optical_flow.html", "classcv_1_1_dense_optical_flow" ],
    [ "DescriptorMatcher", "classcv_1_1_descriptor_matcher.html", "classcv_1_1_descriptor_matcher" ],
    [ "DetectionBasedTracker", "classcv_1_1_detection_based_tracker.html", "classcv_1_1_detection_based_tracker" ],
    [ "DetectionROI", "structcv_1_1_detection_r_o_i.html", "structcv_1_1_detection_r_o_i" ],
    [ "DISOpticalFlow", "classcv_1_1_d_i_s_optical_flow.html", "classcv_1_1_d_i_s_optical_flow" ],
    [ "DMatch", "classcv_1_1_d_match.html", "classcv_1_1_d_match" ],
    [ "DownhillSolver", "classcv_1_1_downhill_solver.html", "classcv_1_1_downhill_solver" ],
    [ "Exception", "classcv_1_1_exception.html", "classcv_1_1_exception" ],
    [ "FarnebackOpticalFlow", "classcv_1_1_farneback_optical_flow.html", "classcv_1_1_farneback_optical_flow" ],
    [ "FastFeatureDetector", "classcv_1_1_fast_feature_detector.html", "classcv_1_1_fast_feature_detector" ],
    [ "Feature2D", "classcv_1_1_feature2_d.html", "classcv_1_1_feature2_d" ],
    [ "FileNode", "classcv_1_1_file_node.html", "classcv_1_1_file_node" ],
    [ "FileNodeIterator", "classcv_1_1_file_node_iterator.html", "classcv_1_1_file_node_iterator" ],
    [ "FileStorage", "classcv_1_1_file_storage.html", "classcv_1_1_file_storage" ],
    [ "FisheyeWarper", "classcv_1_1_fisheye_warper.html", "classcv_1_1_fisheye_warper" ],
    [ "Formatted", "classcv_1_1_formatted.html", "classcv_1_1_formatted" ],
    [ "Formatter", "classcv_1_1_formatter.html", "classcv_1_1_formatter" ],
    [ "GeneralizedHough", "classcv_1_1_generalized_hough.html", "classcv_1_1_generalized_hough" ],
    [ "GeneralizedHoughBallard", "classcv_1_1_generalized_hough_ballard.html", "classcv_1_1_generalized_hough_ballard" ],
    [ "GeneralizedHoughGuil", "classcv_1_1_generalized_hough_guil.html", "classcv_1_1_generalized_hough_guil" ],
    [ "GFTTDetector", "classcv_1_1_g_f_t_t_detector.html", "classcv_1_1_g_f_t_t_detector" ],
    [ "Hamming", "structcv_1_1_hamming.html", "structcv_1_1_hamming" ],
    [ "has_custom_delete", "structcv_1_1has__custom__delete.html", null ],
    [ "has_custom_delete< T, typename std::enable_if< sfinae::has_parenthesis_operator< DefaultDeleter< T >, void, T * >::value >::type >", "structcv_1_1has__custom__delete_3_01_t_00_01typename_01std_1_1enable__if_3_01sfinae_1_1has__pare7a91cf2ae9e9208ae5dd1e38b6bcbf52.html", null ],
    [ "HOGDescriptor", "structcv_1_1_h_o_g_descriptor.html", "structcv_1_1_h_o_g_descriptor" ],
    [ "KalmanFilter", "classcv_1_1_kalman_filter.html", "classcv_1_1_kalman_filter" ],
    [ "KAZE", "classcv_1_1_k_a_z_e.html", "classcv_1_1_k_a_z_e" ],
    [ "KeyPoint", "classcv_1_1_key_point.html", "classcv_1_1_key_point" ],
    [ "KeyPointsFilter", "classcv_1_1_key_points_filter.html", "classcv_1_1_key_points_filter" ],
    [ "L1", "structcv_1_1_l1.html", "structcv_1_1_l1" ],
    [ "L2", "structcv_1_1_l2.html", "structcv_1_1_l2" ],
    [ "LDA", "classcv_1_1_l_d_a.html", "classcv_1_1_l_d_a" ],
    [ "LineIterator", "classcv_1_1_line_iterator.html", "classcv_1_1_line_iterator" ],
    [ "LineSegmentDetector", "classcv_1_1_line_segment_detector.html", "classcv_1_1_line_segment_detector" ],
    [ "LMSolver", "classcv_1_1_l_m_solver.html", "classcv_1_1_l_m_solver" ],
    [ "Mat", "classcv_1_1_mat.html", "classcv_1_1_mat" ],
    [ "Mat_", "classcv_1_1_mat__.html", "classcv_1_1_mat__" ],
    [ "MatAllocator", "classcv_1_1_mat_allocator.html", "classcv_1_1_mat_allocator" ],
    [ "MatCommaInitializer_", "classcv_1_1_mat_comma_initializer__.html", "classcv_1_1_mat_comma_initializer__" ],
    [ "MatConstIterator", "classcv_1_1_mat_const_iterator.html", "classcv_1_1_mat_const_iterator" ],
    [ "MatConstIterator_", "classcv_1_1_mat_const_iterator__.html", "classcv_1_1_mat_const_iterator__" ],
    [ "MatExpr", "classcv_1_1_mat_expr.html", "classcv_1_1_mat_expr" ],
    [ "MatIterator_", "classcv_1_1_mat_iterator__.html", "classcv_1_1_mat_iterator__" ],
    [ "MatOp", "classcv_1_1_mat_op.html", "classcv_1_1_mat_op" ],
    [ "MatSize", "structcv_1_1_mat_size.html", "structcv_1_1_mat_size" ],
    [ "MatStep", "structcv_1_1_mat_step.html", "structcv_1_1_mat_step" ],
    [ "Matx", "classcv_1_1_matx.html", "classcv_1_1_matx" ],
    [ "MatxCommaInitializer", "classcv_1_1_matx_comma_initializer.html", "classcv_1_1_matx_comma_initializer" ],
    [ "MercatorWarper", "classcv_1_1_mercator_warper.html", "classcv_1_1_mercator_warper" ],
    [ "MergeDebevec", "classcv_1_1_merge_debevec.html", "classcv_1_1_merge_debevec" ],
    [ "MergeExposures", "classcv_1_1_merge_exposures.html", "classcv_1_1_merge_exposures" ],
    [ "MergeMertens", "classcv_1_1_merge_mertens.html", "classcv_1_1_merge_mertens" ],
    [ "MergeRobertson", "classcv_1_1_merge_robertson.html", "classcv_1_1_merge_robertson" ],
    [ "MinProblemSolver", "classcv_1_1_min_problem_solver.html", "classcv_1_1_min_problem_solver" ],
    [ "Moments", "classcv_1_1_moments.html", "classcv_1_1_moments" ],
    [ "MSER", "classcv_1_1_m_s_e_r.html", "classcv_1_1_m_s_e_r" ],
    [ "NAryMatIterator", "classcv_1_1_n_ary_mat_iterator.html", "classcv_1_1_n_ary_mat_iterator" ],
    [ "Node", "classcv_1_1_node.html", "classcv_1_1_node" ],
    [ "ORB", "classcv_1_1_o_r_b.html", "classcv_1_1_o_r_b" ],
    [ "PaniniPortraitWarper", "classcv_1_1_panini_portrait_warper.html", "classcv_1_1_panini_portrait_warper" ],
    [ "PaniniWarper", "classcv_1_1_panini_warper.html", "classcv_1_1_panini_warper" ],
    [ "ParallelLoopBody", "classcv_1_1_parallel_loop_body.html", "classcv_1_1_parallel_loop_body" ],
    [ "ParallelLoopBodyLambdaWrapper", "classcv_1_1_parallel_loop_body_lambda_wrapper.html", "classcv_1_1_parallel_loop_body_lambda_wrapper" ],
    [ "ParamType", "structcv_1_1_param_type.html", null ],
    [ "ParamType< _Tp, typename std::enable_if< std::is_enum< _Tp >::value >::type >", "structcv_1_1_param_type_3_01___tp_00_01typename_01std_1_1enable__if_3_01std_1_1is__enum_3_01___t5e0dc426b1b7a3e9231c07f7c045c4cd.html", "structcv_1_1_param_type_3_01___tp_00_01typename_01std_1_1enable__if_3_01std_1_1is__enum_3_01___t5e0dc426b1b7a3e9231c07f7c045c4cd" ],
    [ "ParamType< Algorithm >", "structcv_1_1_param_type_3_01_algorithm_01_4.html", "structcv_1_1_param_type_3_01_algorithm_01_4" ],
    [ "ParamType< bool >", "structcv_1_1_param_type_3_01bool_01_4.html", "structcv_1_1_param_type_3_01bool_01_4" ],
    [ "ParamType< double >", "structcv_1_1_param_type_3_01double_01_4.html", "structcv_1_1_param_type_3_01double_01_4" ],
    [ "ParamType< float >", "structcv_1_1_param_type_3_01float_01_4.html", "structcv_1_1_param_type_3_01float_01_4" ],
    [ "ParamType< int >", "structcv_1_1_param_type_3_01int_01_4.html", "structcv_1_1_param_type_3_01int_01_4" ],
    [ "ParamType< Mat >", "structcv_1_1_param_type_3_01_mat_01_4.html", "structcv_1_1_param_type_3_01_mat_01_4" ],
    [ "ParamType< Scalar >", "structcv_1_1_param_type_3_01_scalar_01_4.html", "structcv_1_1_param_type_3_01_scalar_01_4" ],
    [ "ParamType< std::vector< Mat > >", "structcv_1_1_param_type_3_01std_1_1vector_3_01_mat_01_4_01_4.html", "structcv_1_1_param_type_3_01std_1_1vector_3_01_mat_01_4_01_4" ],
    [ "ParamType< String >", "structcv_1_1_param_type_3_01_string_01_4.html", "structcv_1_1_param_type_3_01_string_01_4" ],
    [ "ParamType< uchar >", "structcv_1_1_param_type_3_01uchar_01_4.html", "structcv_1_1_param_type_3_01uchar_01_4" ],
    [ "ParamType< uint64 >", "structcv_1_1_param_type_3_01uint64_01_4.html", "structcv_1_1_param_type_3_01uint64_01_4" ],
    [ "ParamType< unsigned >", "structcv_1_1_param_type_3_01unsigned_01_4.html", "structcv_1_1_param_type_3_01unsigned_01_4" ],
    [ "PCA", "classcv_1_1_p_c_a.html", "classcv_1_1_p_c_a" ],
    [ "PlaneWarper", "classcv_1_1_plane_warper.html", "classcv_1_1_plane_warper" ],
    [ "Point3_", "classcv_1_1_point3__.html", "classcv_1_1_point3__" ],
    [ "Point_", "classcv_1_1_point__.html", "classcv_1_1_point__" ],
    [ "Ptr", "structcv_1_1_ptr.html", "structcv_1_1_ptr" ],
    [ "PyRotationWarper", "classcv_1_1_py_rotation_warper.html", "classcv_1_1_py_rotation_warper" ],
    [ "QRCodeDetector", "classcv_1_1_q_r_code_detector.html", "classcv_1_1_q_r_code_detector" ],
    [ "QtFont", "structcv_1_1_qt_font.html", "structcv_1_1_qt_font" ],
    [ "Range", "classcv_1_1_range.html", "classcv_1_1_range" ],
    [ "Rect_", "classcv_1_1_rect__.html", "classcv_1_1_rect__" ],
    [ "RNG", "classcv_1_1_r_n_g.html", "classcv_1_1_r_n_g" ],
    [ "RNG_MT19937", "classcv_1_1_r_n_g___m_t19937.html", "classcv_1_1_r_n_g___m_t19937" ],
    [ "RotatedRect", "classcv_1_1_rotated_rect.html", "classcv_1_1_rotated_rect" ],
    [ "Scalar_", "classcv_1_1_scalar__.html", "classcv_1_1_scalar__" ],
    [ "SimilarRects", "classcv_1_1_similar_rects.html", "classcv_1_1_similar_rects" ],
    [ "SimpleBlobDetector", "classcv_1_1_simple_blob_detector.html", "classcv_1_1_simple_blob_detector" ],
    [ "Size_", "classcv_1_1_size__.html", "classcv_1_1_size__" ],
    [ "SL2", "structcv_1_1_s_l2.html", "structcv_1_1_s_l2" ],
    [ "softdouble", "structcv_1_1softdouble.html", "structcv_1_1softdouble" ],
    [ "softfloat", "structcv_1_1softfloat.html", "structcv_1_1softfloat" ],
    [ "SparseMat", "classcv_1_1_sparse_mat.html", "classcv_1_1_sparse_mat" ],
    [ "SparseMat_", "classcv_1_1_sparse_mat__.html", "classcv_1_1_sparse_mat__" ],
    [ "SparseMatConstIterator", "classcv_1_1_sparse_mat_const_iterator.html", "classcv_1_1_sparse_mat_const_iterator" ],
    [ "SparseMatConstIterator_", "classcv_1_1_sparse_mat_const_iterator__.html", "classcv_1_1_sparse_mat_const_iterator__" ],
    [ "SparseMatIterator", "classcv_1_1_sparse_mat_iterator.html", "classcv_1_1_sparse_mat_iterator" ],
    [ "SparseMatIterator_", "classcv_1_1_sparse_mat_iterator__.html", "classcv_1_1_sparse_mat_iterator__" ],
    [ "SparseOpticalFlow", "classcv_1_1_sparse_optical_flow.html", "classcv_1_1_sparse_optical_flow" ],
    [ "SparsePyrLKOpticalFlow", "classcv_1_1_sparse_pyr_l_k_optical_flow.html", "classcv_1_1_sparse_pyr_l_k_optical_flow" ],
    [ "SphericalWarper", "classcv_1_1_spherical_warper.html", "classcv_1_1_spherical_warper" ],
    [ "StereoBM", "classcv_1_1_stereo_b_m.html", "classcv_1_1_stereo_b_m" ],
    [ "StereographicWarper", "classcv_1_1_stereographic_warper.html", "classcv_1_1_stereographic_warper" ],
    [ "StereoMatcher", "classcv_1_1_stereo_matcher.html", "classcv_1_1_stereo_matcher" ],
    [ "StereoSGBM", "classcv_1_1_stereo_s_g_b_m.html", "classcv_1_1_stereo_s_g_b_m" ],
    [ "Stitcher", "classcv_1_1_stitcher.html", "classcv_1_1_stitcher" ],
    [ "Subdiv2D", "classcv_1_1_subdiv2_d.html", "classcv_1_1_subdiv2_d" ],
    [ "SVD", "classcv_1_1_s_v_d.html", "classcv_1_1_s_v_d" ],
    [ "TermCriteria", "classcv_1_1_term_criteria.html", "classcv_1_1_term_criteria" ],
    [ "TickMeter", "classcv_1_1_tick_meter.html", "classcv_1_1_tick_meter" ],
    [ "TLSData", "classcv_1_1_t_l_s_data.html", "classcv_1_1_t_l_s_data" ],
    [ "TLSDataContainer", "classcv_1_1_t_l_s_data_container.html", "classcv_1_1_t_l_s_data_container" ],
    [ "Tonemap", "classcv_1_1_tonemap.html", "classcv_1_1_tonemap" ],
    [ "TonemapDrago", "classcv_1_1_tonemap_drago.html", "classcv_1_1_tonemap_drago" ],
    [ "TonemapMantiuk", "classcv_1_1_tonemap_mantiuk.html", "classcv_1_1_tonemap_mantiuk" ],
    [ "TonemapReinhard", "classcv_1_1_tonemap_reinhard.html", "classcv_1_1_tonemap_reinhard" ],
    [ "TransverseMercatorWarper", "classcv_1_1_transverse_mercator_warper.html", "classcv_1_1_transverse_mercator_warper" ],
    [ "UMat", "classcv_1_1_u_mat.html", "classcv_1_1_u_mat" ],
    [ "UMatData", "structcv_1_1_u_mat_data.html", "structcv_1_1_u_mat_data" ],
    [ "v_reg", "structcv_1_1v__reg.html", "structcv_1_1v__reg" ],
    [ "V_TypeTraits", "structcv_1_1_v___type_traits.html", null ],
    [ "VariationalRefinement", "classcv_1_1_variational_refinement.html", "classcv_1_1_variational_refinement" ],
    [ "Vec", "classcv_1_1_vec.html", "classcv_1_1_vec" ],
    [ "VecCommaInitializer", "classcv_1_1_vec_comma_initializer.html", "classcv_1_1_vec_comma_initializer" ],
    [ "VideoCapture", "classcv_1_1_video_capture.html", "classcv_1_1_video_capture" ],
    [ "VideoWriter", "classcv_1_1_video_writer.html", "classcv_1_1_video_writer" ],
    [ "WarperCreator", "classcv_1_1_warper_creator.html", "classcv_1_1_warper_creator" ]
];