/*
@licstart  The following is the entire license notice for the
JavaScript code in this file.

Copyright (C) 1997-2019 by Dimitri van Heesch

This program is free software; you can redistribute it and/or modify
it under the terms of version 2 of the GNU General Public License as published by
the Free Software Foundation

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License along
with this program; if not, write to the Free Software Foundation, Inc.,
51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.

@licend  The above is the entire license notice
for the JavaScript code in this file
*/
var NAVTREE =
[
  [ "Nymble", "index.html", [
    [ "julia_recipe_engine", "md__r_e_a_d_m_e.html", null ],
    [ "Todo List", "todo.html", null ],
    [ "Deprecated List", "deprecated.html", null ],
    [ "Modules", "modules.html", "modules" ],
    [ "Packages", "namespaces.html", [
      [ "Packages", "namespaces.html", "namespaces_dup" ],
      [ "Package Functions", "namespacemembers.html", [
        [ "All", "namespacemembers.html", "namespacemembers_dup" ],
        [ "Functions", "namespacemembers_func.html", "namespacemembers_func" ],
        [ "Variables", "namespacemembers_vars.html", "namespacemembers_vars" ],
        [ "Typedefs", "namespacemembers_type.html", null ],
        [ "Enumerations", "namespacemembers_enum.html", null ],
        [ "Enumerator", "namespacemembers_eval.html", "namespacemembers_eval" ]
      ] ]
    ] ],
    [ "Classes", "annotated.html", [
      [ "Class List", "annotated.html", "annotated_dup" ],
      [ "Class Index", "classes.html", null ],
      [ "Class Hierarchy", "hierarchy.html", "hierarchy" ],
      [ "Class Members", "functions.html", [
        [ "All", "functions.html", "functions_dup" ],
        [ "Functions", "functions_func.html", "functions_func" ],
        [ "Variables", "functions_vars.html", "functions_vars" ],
        [ "Typedefs", "functions_type.html", null ],
        [ "Enumerations", "functions_enum.html", null ],
        [ "Enumerator", "functions_eval.html", "functions_eval" ],
        [ "Properties", "functions_prop.html", null ],
        [ "Related Functions", "functions_rela.html", null ]
      ] ]
    ] ],
    [ "Files", "files.html", [
      [ "File List", "files.html", "files_dup" ],
      [ "File Members", "globals.html", [
        [ "All", "globals.html", "globals_dup" ],
        [ "Functions", "globals_func.html", "globals_func" ],
        [ "Variables", "globals_vars.html", "globals_vars" ],
        [ "Typedefs", "globals_type.html", null ],
        [ "Enumerations", "globals_enum.html", null ],
        [ "Enumerator", "globals_eval.html", "globals_eval" ],
        [ "Macros", "globals_defs.html", "globals_defs" ]
      ] ]
    ] ],
    [ "Examples", "examples.html", "examples" ]
  ] ]
];

var NAVTREEINDEX =
[
"_a_d_s1115_8cpp.html",
"_component_enums_8h.html",
"_engine_8java.html",
"_hardware_message_parser_enums_8h.html#abb60c9f7ca15068a776cc08a7c08df64",
"_inferred_result_test_8java.html",
"_micro_dispense_enums_8h.html#abeb7fdfd623c767faf8cb13d07dca0f5",
"_progress_data_test_8java.html",
"_value_saver_component_8java.html",
"autogenerated_2opencl__clamdfft_8hpp.html#a1254708bf63f9bc4b0a1a9d7c2952616",
"autogenerated_2opencl__core_8hpp.html#ada7773b01c3021eddccb1b39e7364bdc",
"base_8hpp.html#a759fa1af92f7aa7377c76ffb142abccaa4860313ddd694922075df8e524e3f4bb",
"calib3d_8hpp.html#gga4bb30260c91cf16302d400008c824416a5b5ef5178c5c5d50cc15719aecc5fd25",
"class_component_request.html#ad02d5a02076b962189f0a381f5ff01b5",
"class_input_voltage.html#a42c5430ba9e1d77411329af272b4082f",
"class_pwm_request.html#a34ceb51daa267753c2b09212eec58135",
"classcom_1_1example_1_1recipeengine_1_1instruction_1_1cook_1_1_cook.html",
"classcom_1_1example_1_1recipeengine_1_1instruction_1_1dispense_1_1decorator_1_1_dispensed_quantity_decorator_test.html#a387fc0e03fcecea3454eff4fafe25a57",
"classcom_1_1example_1_1recipeengine_1_1instruction_1_1handler_1_1cook_1_1frying_1_1_frying_cooking_handler_test.html",
"classcom_1_1example_1_1recipeengine_1_1instruction_1_1handler_1_1dispense_1_1blocks_1_1dispense_1_1_dispense_hw_information.html#a7bb9561bb4af81710d3c60e611fbc28b",
"classcom_1_1example_1_1recipeengine_1_1instruction_1_1task_1_1capture_1_1base_1_1_base_capturable_task.html#ac6a0e51a0d62bd8eb3b2b89135e1c2c9",
"classcom_1_1example_1_1recipeengine_1_1util_1_1debug_1_1components_1_1cb_1_1_output_pins_cb_component.html#a935a81ace2307f1b97a063821836cf5a",
"classcom_1_1example_1_1recipeengine_1_1util_1_1debug_1_1components_1_1system_1_1_pcb_temp_system_component.html#ac11c4b30f885c377a032ddb962f63a7c",
"classcv_1_1_a_k_a_z_e.html",
"classcv_1_1_c_l_a_h_e.html#a930a5a9e4eb812a0bf90f8b4defe3583",
"classcv_1_1_data_type_3_01float_01_4.html#a10f82dbe5de5c452fbf93ca4d5e2af45",
"classcv_1_1_file_node.html#a842bed8bad355e523f6161f16cc583e3a6742683e1af0c25240191f756e278c29",
"classcv_1_1_l_d_a.html#abfe6e11fba50470efba487829e099077",
"classcv_1_1_mat__.html#a969438335ef8bb3da5232322e564d62b",
"classcv_1_1_matx.html#a03e916d291e4922a0e96ea638b32066e",
"classcv_1_1_q_r_code_detector.html#aea74bdc71e807a8f0ec691d56b07019d",
"classcv_1_1_sparse_mat_iterator.html#a302209fba84cdd382c3c0ae7b6e3a064",
"classcv_1_1_tonemap_reinhard.html#ab98adb83ee5f4018236a1f33ff366560",
"classcv_1_1cuda_1_1_device_info.html#af72c434adf30a6b60f977dffe3e926b0",
"classcv_1_1detail_1_1_cylindrical_portrait_warper.html#a7bd422c0430eafe4949be6933e24c7de",
"classcv_1_1dnn_1_1_classification_model.html#a915179684a5fb390cc02568bea884a71",
"classcv_1_1instr_1_1_node_data.html#ae8371dee470cf131e820185609234fe7",
"classcv_1_1ocl_1_1_timer.html#adf6487aa9d91d2282201b197b9bd41d3",
"classsom_1_1hardware_1_1response_1_1_sensor_response_test.html",
"core_2hal_2hal_8hpp.html#ga85dc4855552f3a522426a548b8477808",
"cuda_2utility_8hpp_source.html",
"data_8h.html#adb92aee191bc6358871d2a2b8587b39c",
"dir_900273f80e34a702f71edce5543b6192.html",
"dnn_8hpp.html",
"enumsom_1_1instruction_1_1request_1_1sensor_1_1_sensors.html#a682dcc7118ad7ead2d478b5fd41fdfa2",
"gcgraph_8hpp_source.html",
"group__calib3d.html#ggae47e362ab6bd9ea60b7c0c75495e8f7ba51df9c05343c61ddb18324ded0fab86a",
"group__core__basic.html#ga2ac31d988d1a8b5fb959d395dba89890",
"group__core__c.html#ga1a8b3af5e43cd3fe8907cb220bd375f4",
"group__core__c.html#ga4a9109043132264f735b34dfe38389cc",
"group__core__c.html#ga8756ec1a3413bfc233ec687417d02400",
"group__core__c.html#gac3215974887268671a680fb9538d6fe3",
"group__core__c.html#gaf8a8b087b4160ded4619f0fb4c3a644c",
"group__core__hal__functions.html#gac7d501b600a0f2adce404074496a68aa",
"group__core__hal__intrin.html#ga3f3a248d8a6078b73be09883bf2a5108",
"group__core__utils.html#ga162f97ee2c098c61678ece8ae663f4d9",
"group__core__utils.html#gaba229c43c86988330cd5a0565e9bac39",
"group__core__utils__softfloat.html#ga41d1ce4c2aa460c7bab806cb77136d14",
"group__features2d__draw.html#ga39a2112969b7952a816e3f3f5850e0a3",
"group__highgui__c.html#gga5a77d65f4abba81d4456fa6ba8136e24a862e59cc3081a26b22d967a5bb701f02",
"group__imgproc__c.html#ga473ad7afd12dfd7f50bfdb121546ecf4",
"group__imgproc__c.html#gae0a763a40e2455faa17650da84d30413",
"group__imgproc__c.html#ggaea33efd5e2c69d615faad5c5965510aaa0b6a4c2b8da12a242591fd67d787f287",
"group__imgproc__c.html#ggaea33efd5e2c69d615faad5c5965510aaaab0efe2c0209baa41c9e0fb79a6f352c",
"group__imgproc__color__conversions.html#gga4e0972be5de079fed4e3a10e24ef5ef0a8ce54170c486e2deddac3aff035f4af7",
"group__imgproc__hal__functions.html#ga5eeaa45fdda39ed3659e74e703c2fd1c",
"group__imgproc__transform.html#gga5bb5a1fea74ea38e1a5445ca803ff121aa48be1c433186c4eae1ea86aa0ca75ba",
"group__videoio__flags__base.html#ggaeb8dd9c89c10a5c63c139bf7c4f5704daaac79210a04c7a75815be9dfbf78eaf1",
"group__videoio__flags__others.html#ggad3c7afd06d698dd0a307b61cff2211daa4d176582d7510d1dd24816916134178f",
"imgcodecs_8hpp.html#ggaa60044d347ffd187161b5ec9ea2ef2f9a4663acb92a49bb13104a2769cee7d0c8",
"imgproc_8hpp.html#gga0f9314ea6e35f99bb23f29567fc16e11a08cf3b0a37729fbb62a3007d499cbd8b",
"imgproc_8hpp.html#gga7be549266bad7b2e6a04db49827f9f32ada67be24f4dce6d7e6c57527f8724f3b",
"interfacecom_1_1example_1_1recipeengine_1_1instruction_1_1handler_1_1cook_1_1status_1_1_base_inst_status.html#a5bb2e2494c65ca21b2c50ce339c80130",
"intrin__cpp_8hpp.html#gaee2294820f9781e0e09736b6e5201c56",
"namespacecom_1_1example_1_1recipeengine_1_1instruction_1_1cook_1_1params_1_1action.html",
"namespacemembers_func_f.html",
"opengl_8hpp.html#gae899c0266461d15d478e039956b31a5e",
"simplex__downhill_8h_source.html",
"struct_cv_rect.html",
"structcv_1_1_param_type_3_01std_1_1vector_3_01_mat_01_4_01_4.html#a4888173117027981f98e76c7fd1b1cfe",
"structcv_1_1dnn_1_1_dict_value.html#a19df895cf4d23414e0872ec4f2ab8f94",
"types_8hpp_source.html",
"videoio_2legacy_2constants__c_8h.html#a7ada2556f3c386db5f31969fb6d4d002a76e0c823e705fd857dd996ca031d91b2",
"videoio_8hpp.html#gga6a0e727e07d18ebc315bfe86a01f7746a0582602575f693d8cf9f9da68f8d7e4e",
"videoio_8hpp.html#ggaeb8dd9c89c10a5c63c139bf7c4f5704da73f3ec06cf4f9aca1ab7f3b52260fd5e"
];

var SYNCONMSG = 'click to disable panel synchronisation';
var SYNCOFFMSG = 'click to enable panel synchronisation';